### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by arkgil**

### CODE REVIEW

**Review by josevalim — DISMISSED** [review]

**Comment by josevalim** [comment]
Hrm, why CI can't find telemtry 1.0.0? 🤔

**Comment by arkgil** [comment]
It has something to do with rebar version. When I tried with 3.6.1 locally, it wouldn't find it either.

3.16.1, which works locally, doesn't seem to work with OTP 20.

**Comment by josevalim** [comment]
I think it is fine to bump CI to OTP 21, given OTP 20 is no longer supported.

**Comment by arkgil** [comment]
@josevalim same thing with OTP 21. I'll try to figure out the rebar version we can use tomorrow.

**Comment by josevalim** [comment]
Yeah, 21 is not supported either. I think rebar 3.14 was the last one to support all the way back.

**Comment by arkgil** [comment]
3.14 can't fetch telemetry either :/ I'll file a bug with rebar, unless you have more ideas.

**Comment by josevalim** [comment]
Ping. :)

**Comment by arkgil** [comment]
Apologies, I've been swamped the past month and couldn't really make any progress here. I plan to get back to it soon.

**Comment by arkgil** [comment]
Looks like rebar3 3.14.4 and dropping OTP 20 does the trick. I'll amend the PR to drop 20-specific code, add a changelog entry, and it should be good!

**Review by josevalim — DISMISSED** [review]
Awesome! ❤️ i think this is fine, given not even 21 is supported anymore.

**Comment by arkgil** [comment]
Published 🎉

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
